export{default as Home} from './Home'
export{default as Menu} from './Menu'
export{default as About} from './About'
export{default as Order} from './Order'
export{default as Reservation} from './Reservation'
export{default as Contact} from './Contact'
export{default as Cart} from './Cart'
export{default as Login} from './Login'
